/**
 * This class is generated by jOOQ
 */
package com.ankur.project.tables;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Task extends org.jooq.impl.TableImpl<com.ankur.project.tables.records.TaskRecord> {

	private static final long serialVersionUID = 1297470863;

	/**
	 * The singleton instance of <code>public.task</code>
	 */
	public static final com.ankur.project.tables.Task TASK = new com.ankur.project.tables.Task();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<com.ankur.project.tables.records.TaskRecord> getRecordType() {
		return com.ankur.project.tables.records.TaskRecord.class;
	}

	/**
	 * The column <code>public.task.userId</code>.
	 */
	public final org.jooq.TableField<com.ankur.project.tables.records.TaskRecord, java.lang.Long> USERID = createField("userId", org.jooq.impl.SQLDataType.BIGINT, this, "");

	/**
	 * The column <code>public.task.taskName</code>.
	 */
	public final org.jooq.TableField<com.ankur.project.tables.records.TaskRecord, java.lang.String> TASKNAME = createField("taskName", org.jooq.impl.SQLDataType.VARCHAR.length(30), this, "");

	/**
	 * The column <code>public.task.dueDate</code>.
	 */
	public final org.jooq.TableField<com.ankur.project.tables.records.TaskRecord, java.lang.String> DUEDATE = createField("dueDate", org.jooq.impl.SQLDataType.VARCHAR.length(20), this, "");

	/**
	 * The column <code>public.task.timeToCompleteTask</code>.
	 */
	public final org.jooq.TableField<com.ankur.project.tables.records.TaskRecord, java.lang.String> TIMETOCOMPLETETASK = createField("timeToCompleteTask", org.jooq.impl.SQLDataType.VARCHAR.length(10), this, "");

	/**
	 * The column <code>public.task.taskDetails</code>.
	 */
	public final org.jooq.TableField<com.ankur.project.tables.records.TaskRecord, java.lang.String> TASKDETAILS = createField("taskDetails", org.jooq.impl.SQLDataType.VARCHAR.length(200), this, "");

	/**
	 * The column <code>public.task.taskId</code>.
	 */
	public final org.jooq.TableField<com.ankur.project.tables.records.TaskRecord, java.lang.Long> TASKID = createField("taskId", org.jooq.impl.SQLDataType.BIGINT.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>public.task</code> table reference
	 */
	public Task() {
		this("task", null);
	}

	/**
	 * Create an aliased <code>public.task</code> table reference
	 */
	public Task(java.lang.String alias) {
		this(alias, com.ankur.project.tables.Task.TASK);
	}

	private Task(java.lang.String alias, org.jooq.Table<com.ankur.project.tables.records.TaskRecord> aliased) {
		this(alias, aliased, null);
	}

	private Task(java.lang.String alias, org.jooq.Table<com.ankur.project.tables.records.TaskRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, com.ankur.project.Public.PUBLIC, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<com.ankur.project.tables.records.TaskRecord, java.lang.Long> getIdentity() {
		return com.ankur.project.Keys.IDENTITY_TASK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<com.ankur.project.tables.records.TaskRecord> getPrimaryKey() {
		return com.ankur.project.Keys.TASK_PKEY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<com.ankur.project.tables.records.TaskRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<com.ankur.project.tables.records.TaskRecord>>asList(com.ankur.project.Keys.TASK_PKEY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<com.ankur.project.tables.records.TaskRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<com.ankur.project.tables.records.TaskRecord, ?>>asList(com.ankur.project.Keys.TASK__USERID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public com.ankur.project.tables.Task as(java.lang.String alias) {
		return new com.ankur.project.tables.Task(alias, this);
	}

	/**
	 * Rename this table
	 */
	public com.ankur.project.tables.Task rename(java.lang.String name) {
		return new com.ankur.project.tables.Task(name, null);
	}
}
