/**
 * This class is generated by jOOQ
 */
package com.ankur.project.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TaskRecord extends org.jooq.impl.UpdatableRecordImpl<com.ankur.project.tables.records.TaskRecord> implements org.jooq.Record6<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = -1882493023;

	/**
	 * Setter for <code>public.task.userId</code>.
	 */
	public void setUserid(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.task.userId</code>.
	 */
	public java.lang.Long getUserid() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.task.taskName</code>.
	 */
	public void setTaskname(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.task.taskName</code>.
	 */
	public java.lang.String getTaskname() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.task.dueDate</code>.
	 */
	public void setDuedate(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.task.dueDate</code>.
	 */
	public java.lang.String getDuedate() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.task.timeToCompleteTask</code>.
	 */
	public void setTimetocompletetask(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.task.timeToCompleteTask</code>.
	 */
	public java.lang.String getTimetocompletetask() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.task.taskDetails</code>.
	 */
	public void setTaskdetails(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.task.taskDetails</code>.
	 */
	public java.lang.String getTaskdetails() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.task.taskId</code>.
	 */
	public void setTaskid(java.lang.Long value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.task.taskId</code>.
	 */
	public java.lang.Long getTaskid() {
		return (java.lang.Long) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.ankur.project.tables.Task.TASK.USERID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.ankur.project.tables.Task.TASK.TASKNAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.ankur.project.tables.Task.TASK.DUEDATE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.ankur.project.tables.Task.TASK.TIMETOCOMPLETETASK;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.ankur.project.tables.Task.TASK.TASKDETAILS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field6() {
		return com.ankur.project.tables.Task.TASK.TASKID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getUserid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getTaskname();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getDuedate();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getTimetocompletetask();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getTaskdetails();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value6() {
		return getTaskid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRecord value1(java.lang.Long value) {
		setUserid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRecord value2(java.lang.String value) {
		setTaskname(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRecord value3(java.lang.String value) {
		setDuedate(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRecord value4(java.lang.String value) {
		setTimetocompletetask(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRecord value5(java.lang.String value) {
		setTaskdetails(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRecord value6(java.lang.Long value) {
		setTaskid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public TaskRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.Long value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached TaskRecord
	 */
	public TaskRecord() {
		super(com.ankur.project.tables.Task.TASK);
	}

	/**
	 * Create a detached, initialised TaskRecord
	 */
	public TaskRecord(java.lang.Long userid, java.lang.String taskname, java.lang.String duedate, java.lang.String timetocompletetask, java.lang.String taskdetails, java.lang.Long taskid) {
		super(com.ankur.project.tables.Task.TASK);

		setValue(0, userid);
		setValue(1, taskname);
		setValue(2, duedate);
		setValue(3, timetocompletetask);
		setValue(4, taskdetails);
		setValue(5, taskid);
	}
}
