/**
 * This class is generated by jOOQ
 */
package com.ankur.project.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class UserRecord extends org.jooq.impl.UpdatableRecordImpl<com.ankur.project.tables.records.UserRecord> implements org.jooq.Record13<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Long> {

	private static final long serialVersionUID = 49964437;

	/**
	 * Setter for <code>public.user.id</code>.
	 */
	public void setId(java.lang.Long value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>public.user.id</code>.
	 */
	public java.lang.Long getId() {
		return (java.lang.Long) getValue(0);
	}

	/**
	 * Setter for <code>public.user.name</code>.
	 */
	public void setName(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>public.user.name</code>.
	 */
	public java.lang.String getName() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>public.user.email</code>.
	 */
	public void setEmail(java.lang.String value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>public.user.email</code>.
	 */
	public java.lang.String getEmail() {
		return (java.lang.String) getValue(2);
	}

	/**
	 * Setter for <code>public.user.password</code>.
	 */
	public void setPassword(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>public.user.password</code>.
	 */
	public java.lang.String getPassword() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>public.user.gender</code>.
	 */
	public void setGender(java.lang.String value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>public.user.gender</code>.
	 */
	public java.lang.String getGender() {
		return (java.lang.String) getValue(4);
	}

	/**
	 * Setter for <code>public.user.token</code>.
	 */
	public void setToken(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>public.user.token</code>.
	 */
	public java.lang.String getToken() {
		return (java.lang.String) getValue(5);
	}

	/**
	 * Setter for <code>public.user.height</code>.
	 */
	public void setHeight(java.lang.String value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>public.user.height</code>.
	 */
	public java.lang.String getHeight() {
		return (java.lang.String) getValue(6);
	}

	/**
	 * Setter for <code>public.user.weight</code>.
	 */
	public void setWeight(java.lang.Long value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>public.user.weight</code>.
	 */
	public java.lang.Long getWeight() {
		return (java.lang.Long) getValue(7);
	}

	/**
	 * Setter for <code>public.user.age</code>.
	 */
	public void setAge(java.lang.Long value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>public.user.age</code>.
	 */
	public java.lang.Long getAge() {
		return (java.lang.Long) getValue(8);
	}

	/**
	 * Setter for <code>public.user.current_fitness</code>.
	 */
	public void setCurrentFitness(java.lang.String value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>public.user.current_fitness</code>.
	 */
	public java.lang.String getCurrentFitness() {
		return (java.lang.String) getValue(9);
	}

	/**
	 * Setter for <code>public.user.fitness_goals</code>.
	 */
	public void setFitnessGoals(java.lang.String value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>public.user.fitness_goals</code>.
	 */
	public java.lang.String getFitnessGoals() {
		return (java.lang.String) getValue(10);
	}

	/**
	 * Setter for <code>public.user.user_comment</code>.
	 */
	public void setUserComment(java.lang.String value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>public.user.user_comment</code>.
	 */
	public java.lang.String getUserComment() {
		return (java.lang.String) getValue(11);
	}

	/**
	 * Setter for <code>public.user.total_task_completed</code>.
	 */
	public void setTotalTaskCompleted(java.lang.Long value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>public.user.total_task_completed</code>.
	 */
	public java.lang.Long getTotalTaskCompleted() {
		return (java.lang.Long) getValue(12);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Long> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record13 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Long> fieldsRow() {
		return (org.jooq.Row13) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row13<java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.Long, java.lang.Long, java.lang.String, java.lang.String, java.lang.String, java.lang.Long> valuesRow() {
		return (org.jooq.Row13) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field1() {
		return com.ankur.project.tables.User.USER.ID;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return com.ankur.project.tables.User.USER.NAME;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field3() {
		return com.ankur.project.tables.User.USER.EMAIL;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return com.ankur.project.tables.User.USER.PASSWORD;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field5() {
		return com.ankur.project.tables.User.USER.GENDER;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return com.ankur.project.tables.User.USER.TOKEN;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field7() {
		return com.ankur.project.tables.User.USER.HEIGHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field8() {
		return com.ankur.project.tables.User.USER.WEIGHT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field9() {
		return com.ankur.project.tables.User.USER.AGE;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field10() {
		return com.ankur.project.tables.User.USER.CURRENT_FITNESS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field11() {
		return com.ankur.project.tables.User.USER.FITNESS_GOALS;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field12() {
		return com.ankur.project.tables.User.USER.USER_COMMENT;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Long> field13() {
		return com.ankur.project.tables.User.USER.TOTAL_TASK_COMPLETED;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value3() {
		return getEmail();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getPassword();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value5() {
		return getGender();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getToken();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value7() {
		return getHeight();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value8() {
		return getWeight();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value9() {
		return getAge();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value10() {
		return getCurrentFitness();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value11() {
		return getFitnessGoals();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value12() {
		return getUserComment();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Long value13() {
		return getTotalTaskCompleted();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value1(java.lang.Long value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value2(java.lang.String value) {
		setName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value3(java.lang.String value) {
		setEmail(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value4(java.lang.String value) {
		setPassword(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value5(java.lang.String value) {
		setGender(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value6(java.lang.String value) {
		setToken(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value7(java.lang.String value) {
		setHeight(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value8(java.lang.Long value) {
		setWeight(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value9(java.lang.Long value) {
		setAge(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value10(java.lang.String value) {
		setCurrentFitness(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value11(java.lang.String value) {
		setFitnessGoals(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value12(java.lang.String value) {
		setUserComment(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord value13(java.lang.Long value) {
		setTotalTaskCompleted(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public UserRecord values(java.lang.Long value1, java.lang.String value2, java.lang.String value3, java.lang.String value4, java.lang.String value5, java.lang.String value6, java.lang.String value7, java.lang.Long value8, java.lang.Long value9, java.lang.String value10, java.lang.String value11, java.lang.String value12, java.lang.Long value13) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached UserRecord
	 */
	public UserRecord() {
		super(com.ankur.project.tables.User.USER);
	}

	/**
	 * Create a detached, initialised UserRecord
	 */
	public UserRecord(java.lang.Long id, java.lang.String name, java.lang.String email, java.lang.String password, java.lang.String gender, java.lang.String token, java.lang.String height, java.lang.Long weight, java.lang.Long age, java.lang.String currentFitness, java.lang.String fitnessGoals, java.lang.String userComment, java.lang.Long totalTaskCompleted) {
		super(com.ankur.project.tables.User.USER);

		setValue(0, id);
		setValue(1, name);
		setValue(2, email);
		setValue(3, password);
		setValue(4, gender);
		setValue(5, token);
		setValue(6, height);
		setValue(7, weight);
		setValue(8, age);
		setValue(9, currentFitness);
		setValue(10, fitnessGoals);
		setValue(11, userComment);
		setValue(12, totalTaskCompleted);
	}
}
