/**
 * This class is generated by jOOQ
 */
package com.ankur.project;

/**
 * This class is generated by jOOQ.
 *
 * A class modelling foreign key relationships between tables of the <code>public</code> 
 * schema
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<com.ankur.project.tables.records.TaskRecord, java.lang.Long> IDENTITY_TASK = Identities0.IDENTITY_TASK;
	public static final org.jooq.Identity<com.ankur.project.tables.records.UserRecord, java.lang.Long> IDENTITY_USER = Identities0.IDENTITY_USER;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<com.ankur.project.tables.records.TaskRecord> TASK_PKEY = UniqueKeys0.TASK_PKEY;
	public static final org.jooq.UniqueKey<com.ankur.project.tables.records.UserRecord> ID = UniqueKeys0.ID;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<com.ankur.project.tables.records.TaskRecord, com.ankur.project.tables.records.UserRecord> TASK__USERID = ForeignKeys0.TASK__USERID;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<com.ankur.project.tables.records.TaskRecord, java.lang.Long> IDENTITY_TASK = createIdentity(com.ankur.project.tables.Task.TASK, com.ankur.project.tables.Task.TASK.TASKID);
		public static org.jooq.Identity<com.ankur.project.tables.records.UserRecord, java.lang.Long> IDENTITY_USER = createIdentity(com.ankur.project.tables.User.USER, com.ankur.project.tables.User.USER.ID);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<com.ankur.project.tables.records.TaskRecord> TASK_PKEY = createUniqueKey(com.ankur.project.tables.Task.TASK, com.ankur.project.tables.Task.TASK.TASKID);
		public static final org.jooq.UniqueKey<com.ankur.project.tables.records.UserRecord> ID = createUniqueKey(com.ankur.project.tables.User.USER, com.ankur.project.tables.User.USER.ID);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<com.ankur.project.tables.records.TaskRecord, com.ankur.project.tables.records.UserRecord> TASK__USERID = createForeignKey(com.ankur.project.Keys.ID, com.ankur.project.tables.Task.TASK, com.ankur.project.tables.Task.TASK.USERID);
	}
}
