/**
 * This class is generated by jOOQ
 */
package com.ankur.project;

/**
 * This class is generated by jOOQ.
 *
 * Convenience access to all tables in public
 */
@javax.annotation.Generated(value    = { "http://www.jooq.org", "3.3.2" },
                            comments = "This class is generated by jOOQ")
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table public.task
	 */
	public static final com.ankur.project.tables.Task TASK = com.ankur.project.tables.Task.TASK;

	/**
	 * The table public.user
	 */
	public static final com.ankur.project.tables.User USER = com.ankur.project.tables.User.USER;
}
